In [2]:
import numpy as np
import pandas as pd

# Reading the dataset

In [4]:
df = pd.read_csv('dirty_cafe_sales.csv')

# Cheaking the shape of the dataset:

In [5]:
df.shape

(10000, 8)

# Cheaking the first 5 records:

In [6]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

# Cheaking the information of dataset:

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

# Cheaking the missing values:

In [9]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

# Cheaking duplicate rows:

In [10]:
df.duplicated().sum()

np.int64(0)

# Handling missing values:

In [11]:
numeric_cols = df.select_dtypes(include = np.number).columns
categorical_cols = df.select_dtypes(include = 'object').columns

# Filling numerical missing values with median:

In [12]:
for column in numeric_cols:
    df[column] = df[colomn].fillna(df[column].median())

# Filling categorical missing values with mode:

In [14]:
for column in categorical_cols:
    if df[column].isna().sum(0)>0:
        df[column] = df[column].fillna(df[column].mode()[0])

# Cheaking missing values:

In [17]:
print(" Missing values after handling")
df.isnull().sum()

 Missing values after handling

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

# Cheaking Unique values in categorical columns:

In [20]:
for column in categorical_cols:
    print(f'\n{column}:')
    print(df[column].value_counts().head(10))

Transaction ID:
Transaction ID
TXN_1961373    1
TXN_4977031    1
TXN_4271903    1
TXN_7034554    1
TXN_3160411    1
TXN_2602893    1
TXN_4433211    1
TXN_6699534    1
TXN_4717867    1
TXN_2064365    1
Name: count, dtype: int64

Item:
Item
Juice       1504
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
ERROR        292
Name: count, dtype: int64

Quantity:
Quantity
5          2151
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64

Price Per Unit:
Price Per Unit
3.0        2608
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
UNKNOWN     164
Name: count, dtype: int64

Total Spent:
Total Spent
6.0     1152
12.0     939
3.0      930
4.0      923
20.0     746
15.0     734
8.0      677
10.0     524
2.0      497
9.0      479
Name: count, dtype: int64

Payment Method:
Payment Method
Digital Wallet    4870
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

Location:
Location
Takeaway    6287
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

Transaction Date:
Transaction Date
UNKNOWN       318
ERROR         142
2023-06-16     40
2023-02-06     40
2023-09-21     39
2023-03-13     39
2023-07-24     39
2023-07-21     39
2023-01-05     38
2023-10-22     37
Name: count, dtype: int64

# Cheaking numerical summary:

In [21]:
df.describe()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
count,10000,10000,10000,10000,10000,10000,10000,10000
unique,10000,10,7,8,19,5,4,367
top,TXN_1961373,Juice,5,3.0,6.0,Digital Wallet,Takeaway,UNKNOWN
freq,1,1504,2151,2608,1152,4870,6287,318

# Cheaking duplicates again:

In [23]:
print("Duplicates values after cleaning")
df.duplicated().sum()

Duplicates values after cleaning

np.int64(0)

# Final information of dataset:

In [25]:
print("Final shape of dataset",df.shape)

Final shape of dataset (10000, 8)

In [26]:
print("Final missing values of dataset",df

Final missing values of dataset Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

# Saving prepared dataset:

In [27]:
df.to_csv("Dirty_cafe_prepared2.csv",index=False)

In [28]:
print("The data preparation is completed")

The data preparation is completed